# -*- mode: python ; coding: utf-8 -*-
"""Frozen Windows build. Icons are generated by create_icon.py before this runs."""

a = Analysis(
    ["autoclicker.py"],
    pathex=[],
    binaries=[],
    datas=[("autoclicker.ico", "."), ("autoclicker.png", ".")],
    hiddenimports=["sv_ttk"],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="WindowsAutoclicker",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="autoclicker.ico",
)
